language: php

sudo: false

php:
  - 7.0

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - MYSQL_HOST=127.0.0.1
    - MYSQL_PORT=3306
    - MYSQL_USER=root
    - MYSQL_PASSWORD=""
    - MYSQL_DATABASE=myapp_test

before_script:
  - composer install --prefer-dist
  - mysql -e 'CREATE DATABASE myapp_test'

script:
  - vendor/bin/phpunit --colors
