language: php

sudo: false

php:
  - 7.2

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - MYSQL_HOST=127.0.0.1
    - MYSQL_PORT=3306
    - MYSQL_USER=root
    - MYSQL_PASSWORD=""
    - MYSQL_DATABASE=myapp_test

before_script:
  - mysql -e 'CREATE DATABASE myapp_test'

install:
  - composer install --prefer-dist -o

script:
  - phpunit --version
  - phpunit --colors --coverage-text

before_deploy:
  - php -d phar.readonly=0 box.phar build -v

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dbdatool.phar
  skip_cleanup: true
  on:
    php: 7.2
    tags: true
